### ISSUE TITLE
引入 devtools.js 后部分被作为子节点渲染的组件会被处理为 tag 为 1 的组件，引发 devtools 的报错

### ISSUE THREAD

**Issue by Runtu4378** [RubyLouvre/anu#104]
### Version

1.3.1

### Environment

window10-64，webpack2.2.0，NodeJS8.9.3

### Reproduction link

https://github.com/Runtu4378/react_ie8_demo

### Steps to reproduce

- 提供的例子是没有出现这个问题的，安装完启动之后点击在首页的 banner 下方的白色小圆点能如常出发 `this.setState`
- 将 `src/pages/index/index.js` 第四行的 `require(devtools)`反注释，然后刷新页面
- 发现页面出现 `Uncaught (in promise) TypeError: Cannot read property 'state' of undefined` 的报错，此时页面虽然如常显示，react devtool 的扩展也能正确获取到 react 节点结构，但是此时进行第一步的操作会发现无法正常触发 `this.setState` 事件

### What is expected?

- 能正常使用 react devtool 扩展
- 不影响 setState 事件的正常触发

### What is actually happening?

- devtool.js 内部逻辑报错
- 无法 setState，取消引入 dectool.js 的时候才恢复正常

可能的原因是来源于将  `src/pages/index/index.js` 里面的节点结构 json 转换为节点树的时候部分节点被处理为 tag 为 1 的节点导致的

**Comment by RubyLouvre** [comment]
嗯，这以后会重新开发调试工具。官方的React16也搞了一个新的devtools。
