### ISSUE TITLE
组件在 render 完成前如果有抛出错误, 会导致 后续 组件无法被渲染

### ISSUE THREAD

**Issue by dive2Pro** [RubyLouvre/anu#106]
demo: https://codesandbox.io/s/xzvvmn0qzq

我有看了源码, 发现 mount 过程中, 组件在 render 完成之前抛出的错误, 会根据 doctor 组件可分为下面两种情况: 
1. 有 doctor,  Refs.errorHook 有值, 所以 mountChildren 中的循环会被打断, 造成在 doctor 之后添加的组件都不会进入 updateQueue, 从而无法渲染.

2. 无 doctor, 后续组件会正常渲染.

**Comment by RubyLouvre** [comment]
这个1.4已经修复

**Comment by RubyLouvre** [comment]
1.4已经搞定
