### ISSUE TITLE
the second param of useEffect is invalid.

### ISSUE THREAD

**Issue by BetaSu** [RubyLouvre/anu#1067]
This is React:
https://codepen.io/anon/pen/rEJgMJ?editors=0011
This is Anujs:
https://codepen.io/anon/pen/OeQYzX?editors=0011

You can see , useEffect 's first param is called everytime when state change in Anujs.

version: 1.5.3

**Comment by lizheming** [comment]
https://github.com/RubyLouvre/anu/blob/4ca7bcc6579430d8212db8afd57a7b7a7696e1de/packages/fiber/dispatcher.js#L61 

It seems the problem is callback returned and push to update list array when prevDeps equals to nextDeps.
