### ISSUE TITLE
可以使用react-router-dom吗

### ISSUE THREAD

**Issue by huangxinxia** [RubyLouvre/anu#1100]

**Comment by huangxinxia** [comment]
1.我原本的项目是使用推荐的那个reach路由，然是它好像没法在子组件中获取到当前路由的信息，所以我改用了react-router-dom。
2.使用了react-router-dom，不知道是不是因为不兼容。在IE上无法显示页面，且控制台没有报错（其他浏览器可以正常显示），代码和IE8上的显示如下图：
![微信截图_20190724165411](https://user-images.githubusercontent.com/40933477/61779683-b97c3180-ae33-11e9-9806-3f82c793c7cb.png)
![微信截图_20190724165428](https://user-images.githubusercontent.com/40933477/61779691-bbde8b80-ae33-11e9-8e97-f08670585ac9.png)
3.react-redux，引入以后错误更多了，哭死~

**Comment by huangxinxia** [comment]
5.*版本的react-router-dom是没有任何报错，也不现实。
4.*的react-router-dom是报错，对象不支持“addEventListener”属性或方法

**Comment by RubyLouvre** [comment]
IE8不支持 addEventListener

**Comment by RubyLouvre** [comment]
https://github.com/liyanghawk/react-router-ie8
