### ISSUE TITLE
tabBar可以支持自定义吗？

### ISSUE THREAD

**Issue by kkkdb** [RubyLouvre/anu#1107]
`{
  "tabBar": {
    "custom": true,
    ……
  },
}
`
想自定义tabBar，目前好像不支持

**Comment by RubyLouvre** [comment]
你是指什么平台，我的娜娜奇官网有写，快应用只能贴来最下面

**Comment by kkkdb** [comment]
> 你是指什么平台，我的娜娜奇官网有写，快应用只能贴来最下面

微信平台。custom-tab-bar这个文件夹具体要放哪里？微信是要与与app.js、pages同层的。我试了下nanachi watch:wx或者nanachi build:wx都没有生成custom-tab-bar这个文件。

**Comment by kkkdb** [comment]
还有

**Comment by kkkdb** [comment]
还有
pageLifetimes: {
    show() {
      if (typeof this.getTabBar === 'function' &&
        this.getTabBar()) {
        this.getTabBar().setData({
          selected: 0
        })
      }
    }
  }
