### ISSUE TITLE
input onChange事件输入中文无法触发

### ISSUE THREAD

**Issue by wengrongguo** [RubyLouvre/anu#1125]
** 描述 **
input绑定onChange事件，输入中文时无法触发，直到失去焦点才会触发一次，输入其他字符（数字、字母）无此问题，debug发现输入中文时!dom.__onComposition===false

** 环境 **
浏览器：Chrome(73)
类库：ReactIE(1.5.9)

![image](https://user-images.githubusercontent.com/6010349/62931474-02028b80-bdf1-11e9-943e-b9f5e4c4998e.png)

**Comment by RubyLouvre** [comment]
已经搞定

**Comment by wengrongguo** [comment]
你好，试了一下最新版本，这个问题在chrome依然存在，在IE8下可以触发change事件，但是IE8点击删除键删除字符的时候光标会自动挪动到最前面
