### ISSUE TITLE
IE环境下，类库报错：‘this.state.resolved’为空或不是对象

### ISSUE THREAD

**Issue by wengrongguo** [RubyLouvre/anu#1126]
** 描述 **
IE环境下，类库报错：‘this.state.resolved’为空或不是对象

** 环境 **
浏览器：IE8
类库：ReactIE(1.5.9)

![image](https://user-images.githubusercontent.com/6010349/62989738-e395a200-be7b-11e9-8b62-606d9f9e8e1a.png)

**Comment by RubyLouvre** [comment]
this.state为null  undefined吗？ 你加了Promise polyfill没有？

**Comment by huangxinxia** [comment]
我也有过这个问题，只要版本一改动，就会出现各种问题，你可以各种依赖的版本改动一下。
不知道楼主有么有在IE8上试过，我的项目在IE8上卡爆。我用的是antd的组件库。。。哭晕

**Comment by RubyLouvre** [comment]
想不到是函数声明自动提成到当前作用域的顶部，导致与其他render方法混乱了。我已经修好了。

**Comment by RubyLouvre** [comment]
1.5.10

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/63355081-297cc980-c398-11e9-88fd-6bbab4d92e9d.png)
