### ISSUE TITLE
Can you provide the ability to compile components into webcomponents? Is cross-framework a future trend?能否提供把组件编译成webcomponents的功能？跨框架组件是未来的趋势吗？

### ISSUE THREAD

**Issue by masx200** [RubyLouvre/anu#1155]
能否提供把组件编译成webcomponents的功能？跨框架组件是未来的趋势吗？
希望可以在其他前端框架中共享组件生态。

Can you provide the ability to compile components into webcomponents? Is cross-framework a future trend?
I hope that the component ecosystem can be shared in other front-end frameworks.

### What does the proposed API look like?
```js

import {transformToWebcomponents} from "anu"

import mycomponent from "./mycomponent.jsx"

const MyElement=transformToWebcomponents(mycomponent)

window.customElemnt.define('my-element', MyElement)
```

**Comment by menhal** [comment]
感觉跨框架组件不会是未来趋势, 因为会让组件的设计受到很大限制, 框架的优势无法充分发挥.

**Comment by RubyLouvre** [comment]
不会，webcomponents并不好用。
