### ISSUE TITLE
/lib/ReduxIE.js 里面有低级的括号错误

### ISSUE THREAD

**Issue by foresightyj** [RubyLouvre/anu#1167]
**bug描述**
描述出现的问题
![image](https://user-images.githubusercontent.com/1296736/65238473-4f1ffe80-db0f-11e9-9896-fdf38260df46.png)

**复现bug的步骤**

**问题截图**
![image](https://user-images.githubusercontent.com/1296736/65238497-5d6e1a80-db0f-11e9-9ce7-69c5ccd3eb25.png)

**编译环境信息**
 - nanachi-cli 版本：[e.g.1.2.0]
 - nodejs版本、npm版本：[node v8.11.4、npm 5.6.0]
 - 小程序IDE 版本: [e.g.1.02.1907300]
 - 电脑操作系统： [e.g. macOS High Sierra 10.13.6]

**运行环境信息**
 - 端版本： [e.g. 微信小程序 7.0.3]
 - 手机机型: [e.g. iPhone6 12.0]

**Comment by RubyLouvre** [comment]
好，谢谢反馈
