### ISSUE TITLE
用了IE8脚手架dev tool不显示

### ISSUE THREAD

**Issue by mqliutie** [RubyLouvre/anu#117]
先感谢 [云小飞](https://gitee.com/menhal/React_IE8_boilerplate) 的脚手架

开发中使用dev tool 不显示

![image](https://user-images.githubusercontent.com/11795518/40046429-89b9d1bc-585f-11e8-982d-c5e76850194c.png)

点击多次未果  重启chrome 无效

anujs version : **1.3.4**

**Comment by mqliutie** [comment]
在搜狗浏览器4.0版本跑了一下, 这个脚手架无法正确渲染.尴尬的是这个浏览器还调不出来开发者工具...

**Comment by RubyLouvre** [comment]
IE8加了许多polyfill受到影响吧，就不要用dev tool了
