### ISSUE TITLE
ReactWX.js需要手动拷到dist里吗

### ISSUE THREAD

**Issue by WQfans** [RubyLouvre/anu#1174]
执行watch以后需要手动将拷ReactWX.js拷到dist里，

**Comment by taotao9125** [comment]
> 执行watch以后需要手动将拷ReactWX.js拷到dist里，

美女，不需要的。
watch模式下，自动回把React*.js 拷贝到dist.

**Comment by WQfans** [comment]
在Mac上不需要，我的windows上老是不会自己拷过去
