### ISSUE TITLE
新手建议更新一下脚手架，同步最新的库支持

### ISSUE THREAD

**Issue by appbest** [RubyLouvre/anu#129]
新手建议更新一下脚手架，同步最新的库支持，让新手更容易上手，扩大使用群体。

谢谢作者带来的技术革新

**Comment by appbest** [comment]
anujs的官方脚手架
https://github.com/RubyLouvre/create-anu-app

anujs webpack项目脚手架

https://github.com/Levan-Du/anu-cli

**Comment by appbest** [comment]
reach的官网 适配的 使用dome
https://reach.tech/router

**Comment by RubyLouvre** [comment]
已经列出来了
