### ISSUE TITLE
开发环境下会报React.createElement: type is invalid.错误

### ISSUE THREAD

**Issue by kly402023688** [RubyLouvre/anu#134]
1.3.x的版本不会报这种错误  但是1.3.x版本发现一种情况父组件setState之后 父组件的state确定已经变化 但是 子组件不会触发更新 所以改为1.4.x版本 但是直接报错 在生产环境倒是不会报这种错误

**Comment by RubyLouvre** [comment]
没有例子，无法分析

**Comment by kly402023688** [comment]
好  我去写下demo看看会不会有这个问题 有的话代码放到github上发链接

**Comment by kly402023688** [comment]
\_(:з」∠)\_ 在写demo的时候  反倒把原因都找到了  
1.3.x版本之所以会出现state更新了子组件不会触发更新  是因为根节点的那层组件我用的是react-redux生成的Connect组件  换成自己写的组件然后自己写redux更新的订阅就OK了  不过在react和1.4.x版本用Connect组件不会有问题
至于1.4.4报错则是注释了一大堆组件之后 发现剩下的不再报错  之后去比对两个组件   结果发现是同事写的一些这种组件导致的报错，就是这种组件会报React.createElement: type is invalid这种错误 
这个在1.3.x和react下不会报错
```
function Loading(props) {
   const {text, img, show} = props;
    return (
        <div className={style['loading']} style={{display: show ? 'block' : 'none'}}>
            {props.shadeIsShow?<div className={style['cover']}/>:''}
           <div className={style['info']}>
               <img src={img}/>
                <p>{text}</p>
           </div>
        </div>
    )
}
```

**Comment by RubyLouvre** [comment]
你给于个页面啊，像 ` https://github.com/RubyLouvre/anu/blob/master/index6.html ` 这样写写

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/42011591-a3231cf6-7ac6-11e8-8361-cff99653f3f4.png)
![image](https://user-images.githubusercontent.com/190846/42011605-b6fdb6c8-7ac6-11e8-96aa-7d4358ef6a13.png)

**Comment by kly402023688** [comment]
\_(:з」∠)\_ 我找时间再写下demo  或许还有其他原因影响 =。=   等我上传之后来留地址司徒大神再来看看吧

**Comment by kly402023688** [comment]
\_(:з」∠)\_ 1.3.3版本那问题自己写demo死活重现不出来  最后一狠心copy了项目来删  最后发现自己的demo少了个条件
1.4.4那个在开发环境直接就会有 
github地址:[https://github.com/kly402023688/anu_question](https://github.com/kly402023688/anu_question)

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/42300526-8302e762-8043-11e8-9cba-c5731fda073d.png)
```javascript
//operateChildren有着复杂的逻辑，如果第一层是可遍历对象，那么
export function traverseAllChildren(children, nameSoFar, callback, bookKeeping) {
    let childType = typeNumber(children)
    let invokeCallback = false;
    switch (childType) {
        case 0://undefined
        case 1://null
        case 2://boolean
        case 5://function
        case 6://symbol
            children = null
            invokeCallback = true
            break
        case 3://string 
        case 4://number
            invokeCallback = true
            break
        // 7 array
        case 8://object
            if (children.$$typeof) {
                invokeCallback = true
            } else if (children.hasOwnProperty("toString")) {
                children = children + ""
                invokeCallback = true
                childType = 3;
            }
            break
    }

```
发现问题是出在用了react-hot-loader之后，children是一个对象，跑到case 8这个分支。但children竟然没有$$typeof 属性。因此需要改一下
```javascript
  if (children.$$typeof || children instanceof Component) {
```

此外 Fiber构造器也出错了,因为这个实例也没有type属性，导致type.displayName出错。改成这样好了。
```javascript
export function Fiber (vnode) {
    extend(this, vnode);
    let type = vnode.type || "ProxyComponent(react-hot-loader)";
    this.name = type.displayName || type.name || type;
    this.effectTag = 1;
}
```
在IE8浏览器，不支持hot-loader。因为IE8既不支持Object.defineProperty也不支持Proxy
