### ISSUE TITLE
配套reach ie8兼容性问题

### ISSUE THREAD

**Issue by moyui** [RubyLouvre/anu#138]
在ie8下 报Object.prototype.propertyIsEnumerable: 'this' 不是 JavaScript 对象
例子：https://github.com/moyui/reachtest

**Comment by RubyLouvre** [comment]
你把热加载关闭了试试

**Comment by RubyLouvre** [comment]
去掉 es5-sham  

https://zhuanlan.zhihu.com/p/39103023
