### ISSUE TITLE
依赖包里有webpack3配置的，导致编译失败

### ISSUE THREAD

**Issue by shangcloud** [RubyLouvre/anu#144]
项目里有依赖next库，next用了webpack3配置CommonsChunkPlugin，但webpack4是不支持这个的，导致打包编译失败。
Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
依赖包用的wp3所以项目无法升4，求解决办法。

ps：个人感觉npm发布版可以不加webpack依赖？感觉又没作用，都是自己项目配置的，git源码里配置很正常，这样就可以解决我的问题了？

**Comment by shangcloud** [comment]
赞！期待npm发版

**Comment by RubyLouvre** [comment]
1.4.5发布
