### ISSUE TITLE
IE11下dist/Router.js报错

### ISSUE THREAD

**Issue by finalcat** [RubyLouvre/anu#146]
anujs版本: 1.4.3
系统环境: Win10 64  IE11 
经过排查polyfill.js的Object.assign中的source.hasOwnProperty判断，当source为window.location对象时存在问题
```
   window.location.hasOwnProperty("hash")//ie11下结果为false
```

**Comment by RubyLouvre** [comment]
你是用了 anujs/lib/polyfill.js吗？这个我可以修修
