### ISSUE TITLE
ie8 onchange 未触发问题

### ISSUE THREAD

**Issue by yandeqiang** [RubyLouvre/anu#152]
版本： 1.4.5
问题： 如下代码，onchange 在 ie 下未触发， chrome 正常
```jsx
class App extends React.Component {
  constructor() {
    super();
    this.state = {
      value: null
    };
  }
  render() {
    return (
      <div className="popular">
        <input type="text" onKeyup={() => {
          console.log(111)
        }} onChange={() => {
          console.log(222)
        }}/>
      </div>
    )
  }
}

```

**Comment by RubyLouvre** [comment]
有一个 https://github.com/RubyLouvre/anu-ie8-example 的例子，可以用它改改

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/43306712-9fc765e0-91ae-11e8-8f19-75589efebcea.png)
是没有问题的

**Comment by yandeqiang** [comment]
![image](https://user-images.githubusercontent.com/20136341/43306809-f96ca0c4-91ae-11e8-9ff6-babeee37d169.png)
这是我这的输出结果.

**Comment by RubyLouvre** [comment]
你是加了其他东西影响了吗

**Comment by yandeqiang** [comment]
webpack  alias 配置错误，ie 下应该 
`'react': 'anujs'` => `'react': 'anujs/dist/ReactIE.js'`
