### ISSUE TITLE
need implement addEventListener

### ISSUE THREAD

**Issue by valonY** [RubyLouvre/anu#174]
当我尝试使用ReactIE.js进行在dev模式下的服务端渲染时， 我使用了一个专门的webpack文件来打包文件到node环境，我预期是使用module._compile解析成模块，再调用renderToString来渲染的，问题出错在module._compile解析webpack打包的文件这句代码。永远会报错“need implement addEventListener”，看了下源码这个错误在dev模式下是直接throw掉的，而在node环境下，addEventListener， attachEvent页是不存在的，兼容ie情况下可以做SSR吗？

**Comment by RubyLouvre** [comment]
不知道你说哪里，又没有代码，自己尝试修复一下

**Comment by RubyLouvre** [comment]
好了
