### ISSUE TITLE
请问哪些UI库在anu上测试过

### ISSUE THREAD

**Issue by ambit-tsai** [RubyLouvre/anu#217]
从官网上看到，“支持React生态圈的99％的组件与UI库“，“支持99％的antd组件”这些信息。
而从antd官网得知，antd在2.0以后就不兼容IE8了。
因此，咨询下哪些UI库在anu上测试过，我应该选择什么版本？

**Comment by RubyLouvre** [comment]
antd3

**Comment by RubyLouvre** [comment]
ie8就自己造库吧。别人的库不支持IE8，没有办法
