### ISSUE TITLE
初次安装使用报"Error: Could not resolve './pages/demo/baseContent/base/index' from src\app.js"

### ISSUE THREAD

**Issue by one-pupil** [RubyLouvre/anu#241]
按照博主方法：从“RubyLouvre/anu下” git clone下来， 命令行定义到packages/cli目录下，执行npm link
使用mpreact <project-name> 创建工程
定位到 <project-name> 目录下 mpreact start 开始监听文件变化，
用微信开发工具打开当中的dist目录，自己收在src目录中进行开发.

报了这个错，找到`app.js` 中`import './pages/demo/baseContent/base/index';`这一句注释就能跑起来了，建议修改下。

当我编译后，`dist`目录下并没有生成`app.json`文件。导致程序并不能真正跑起来。

**Comment by RubyLouvre** [comment]
昨天刚改了目录，重拉一下就行了 './pages/demo/baseContent/base/index'; 变成'./pages/demo/base/index';

**Comment by RubyLouvre** [comment]
更多常见问题见这里 https://github.com/RubyLouvre/anu/issues/133#issuecomment-416878188

**Comment by one-pupil** [comment]
^_^
