### ISSUE TITLE
微信开发者工具提示  未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。

### ISSUE THREAD

**Issue by php110** [RubyLouvre/anu#246]
文件变化监控
build success: src\app.json

已编译了，为嘛dist目录里没有对应的文件呢

**Comment by RubyLouvre** [comment]
src目录下是没有app.json，只有dist目录下才有

**Comment by RubyLouvre** [comment]
app.json是通过app.js动态生成出来的

**Comment by php110** [comment]
我改变了app.js，但是dist目录下没有生成app.json，系统是WIN7，node是8.11.4，npm是5.6

**Comment by php110** [comment]
![image](https://user-images.githubusercontent.com/10349965/44891946-bf958b00-ad14-11e8-8029-c747a9bf7427.png)

**Comment by RubyLouvre** [comment]
发现真的在window下js与json文件没有生成出来，应该path的兼容性问题，我们处理一下

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/anu/pull/250/files 同事说修复了

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/44966655-0d0d3480-af6f-11e8-921e-168931ff03fb.png)
