### ISSUE TITLE
Nanachi 文档中存在错别字

### ISSUE THREAD

**Issue by iPixelOldC** [RubyLouvre/anu#302]
错别字位置（https://rubylouvre.github.io/nanachi/documents/component.html）
通用组件一章中组件的样板一节中
> 由于目录可能比较深，因此娜娜美比较贴心地提供了两个默认的*别美*，@react 与@components, @react指向开发目录下的ReactWX.js, @components指向开发目录下的components目录。

是别名不是别美(・ω・｀ll)
（表示找不到文档的仓库，就只能在这发了，如果错了，十分抱歉）

**Comment by iPixelOldC** [comment]
手机排班，十分混乱，抱歉

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/nanachi
 
已改
