### ISSUE TITLE
windows下@components的alias无效

### ISSUE THREAD

**Issue by linbinhuang** [RubyLouvre/anu#318]
报 Could not load g:/project/anu-miniprogram/src/components/pageIndex/index (imported by g:\project\anu-miniprogram\src\pages\index.js): ENOENT: no such file or directory, open 'g:\project\anu-miniprogram\src\components\pageIndex\index';

**Comment by linbinhuang** [comment]
把@components改为相对路径就可以

**Comment by RubyLouvre** [comment]
window操作系统吗？

**Comment by linbinhuang** [comment]
是的

**Comment by RubyLouvre** [comment]
那晚上看看吧，现在没有window

**Comment by linbinhuang** [comment]
奇怪的是，我晚上npm unlink后再npm link，然后再启动就不报错了
