### ISSUE TITLE
这个跟qreact有什么区别，

### ISSUE THREAD

**Issue by Blet** [RubyLouvre/anu#33]

**Comment by lengjing** [comment]
更轻量

**Comment by xuqingkuang** [comment]
现在此类 React alternating 框架已经有了 Preact、工业聚的 React lite、携程的 React、Inferno ，还有司徒大神的 Anu 等等。

我的理解是 React 本身是一个设计理念的最佳实现，周边生态、可实现功能也是最多的（比如 React native）。

别的都是那种设计理念适应各个场景的特定优化，比如 Inferno 的性能，Anu 的 IE6 兼容。

**Comment by RubyLouvre** [comment]
qreact 也是我们公司出的。anu只想让React的应用场合最大化，并提供一个足够迷你的体积。

**Comment by Blet** [comment]
@RubyLouvre 所以在这两个之间，如何做场景选择
