### ISSUE TITLE
mpreact 不能使用decorator？

### ISSUE THREAD

**Issue by nyrf** [RubyLouvre/anu#371]
用了decorator后报错，加.babelrc文件里面设置plugin也没用，

**Comment by RubyLouvre** [comment]
不能，因为考虑转译后会添加大量的代码，导致整体size增大，因此不给支持

**Comment by RubyLouvre** [comment]
我们也不建议用redux，统一用globalData

**Comment by nyrf** [comment]
了解。。谢谢
