### ISSUE TITLE
目前支持 mobx 和 sourceMap 吗？

### ISSUE THREAD

**Issue by lizhoukai** [RubyLouvre/anu#424]

**Comment by lizheming** [comment]
mobx 应该是没问题的，不过要注意如果要兼容 IE 8 的话最好不要用。mobx 用了 getter, setter 在 IE8 上是不兼容的。sourceMap 一直都是支持的，你自己在 webpack.config.js 中配下 devtool 就好了，和 anujs 关系不大。

**Comment by lizhoukai** [comment]
thx
