### ISSUE TITLE
无法正确引用graphql-tag库

### ISSUE THREAD

**Issue by cuijiemmx** [RubyLouvre/anu#481]
重现步骤
1. 使用mpreact创建一个去哪儿模板项目
2. 在项目目录中运行 npm i graphql-tag graphql
3. 打开app.js，在文件开头加入import gql from 'graphql-tag'
4. mpreact build
5. 在微信开发者工具中载入项目
6. 控制台中输出module "npm/graphql/language/parser.js" is not defined

**Comment by cuijiemmx** [comment]
resolveNpm.js中的nodeResolve.sync方法解析出的结果是..../parser.js，然而copy到dist/npm/graphql下的文件是parser.mjs（注意是mjs），已尝试在nodeResolve.sync的opts加入extensions: ['.mjs', '.js']，此时sync能正确地得到parser.mjs，然而控制台仍然会报错，猜想是因为cjs 无法import esm的问题

**Comment by cuijiemmx** [comment]
希望能多测试下引入第三方npm库的功能，感觉这块bug不少

**Comment by cuijiemmx** [comment]
引入第三方库自然是有这样的需求啊，不想重复造轮子
比如我想引入apollo client，实现graphql的查询、缓存和本地状态的自动管理，相应地我会移除@rematch, react-redux这些东西，而且由于apollo提供了强大的功能，需要写的代码更少，所以最后程序包的尺寸差不了多少，也许会大一些，但是开发更快更易维护，性价比杠杠的
以上只是为了解释为啥要引入这么多东西...

另外对于apolloclient的使用，taro是支持的，taro对于第三方库的支持目前看来是最好的。那么我为什么不用taro呢？因为taro对于react的支持很差啊，比如不支持context机制，导致react生态里的库很多没法用。

楼主我们是要解决问题，不是要解决提出问题的人啊

**Comment by RubyLouvre** [comment]
有关娜娜奇的一些细节可看这里  https://rubylouvre.github.io/nanachi/documents/about.html
