### ISSUE TITLE
第三方原生主键引入不能使用

### ISSUE THREAD

**Issue by quqiufeng** [RubyLouvre/anu#503]
usingComponents: {
        'van-icon': '/components/vant-weapp/dist/icon/index',
      }

      使用
     <van-icon name="add-o" size="30px" />

     组件代码  https://github.com/youzan/vant-weapp/tree/dev/dist/icon

     之前用mpreact watch/build 正常

**Comment by quqiufeng** [comment]
显示为空

**Comment by RubyLouvre** [comment]
不支持了，现在要考虑到支持7 种小程序，只能以React方式 写组件
