### ISSUE TITLE
事件回调函数中调用e.preventDefault()后，e.defaultPrevented 仍然为 false

### ISSUE THREAD

**Issue by xilixjd** [RubyLouvre/anu#507]
发现这个 Bug 是在用`react-router`的`Link`的时候
```
<Link onClick={(e) => click(e)} to="/about">About</Link>
function click(e) {
    e.preventDefault()
    console.log(e.defaultPrevented) // 仍然为 false
}
```
按理说在`Link`组件下定义 onClick 并且在回调中调用`e.preventDefault()`，`e.defaultPrevented` 应该为 true，`anu`中目前结果是 false，这样导致了`Link`的跳转依然有效，由于根据`react-router`源码`event.defaultPrevented`为 true 时不跳转。
```
handleClick(event) {
            if (this.props.onClick)
                this.props.onClick(event)

            if (
                !event.defaultPrevented && // 为 true 则不跳转 
                event.button === 0 && // ignore right clicks
                !this.props.target && // let browser handle "target=_blank" etc.
                !isModifiedEvent(event) // ignore clicks with modifier keys
            ) {
                event.preventDefault()

                const { history } = this.context.router
                const { replace, to } = this.props

                if (replace) {
                    history.replace(to)
                } else {
                    history.push(to)
                }
            }
        }
```
根据 anu 的源码
```
preventDefault: function preventDefault() {
            var e = this.nativeEvent || {};
            e.returnValue = this.returnValue = false;
            if (e.preventDefault) {
                e.preventDefault();
            }
        }
```
这里的`e`是原生 event 对象，而最开始`onClick`中的`e`是`SyntheticEvent`对象，而在`anu`中调用原生 event 对象的`e.preventDefault()`方法，`SyntheticEvent`对象的`defaultPrevented`属性值并不改变，改为
```
preventDefault: function preventDefault() {
            var e = this.nativeEvent || {};
            e.returnValue = this.returnValue = false;
            if (e.preventDefault) {
                e.preventDefault();
                this.defaultPrevented = true;
            }
        }
```
即功能正常
在React中测试是正常的，但是不知道他是怎么实现的，这里给个自己的解决方案，也不知道好不好

**Comment by RubyLouvre** [comment]
下个版本修修

**Comment by xilixjd** [comment]
OK
正美哥，能否请教一下 anu/react 为什么要重新实现一套事件系统呢，除了兼容性方面的考虑还有什么原因呢，为什么要把事件都绑在 document 上，然后手动地捕获和冒泡？

**Comment by RubyLouvre** [comment]
## 1.4.9(2018.11.17)

1. 重构小程序dispathEvent与dispatchEventQuick的实现
2. 重构 快应用toStyleQuick
3. 修复miniCreateClass 不能继承父类的类成员的BUG（PC中的React内部的组件继承用到它，及小程序的各种React的toClass方法的本体就是它）
4. 修复事件回调函数中调用e.preventDefault()后，e.defaultPrevented 仍然为 false
5. 修复用iframe打开一个新页面 document.adctiveElement 抛出异常，导致无法渲染的BUG
6. 修复 devtools 的两个问题
   -  点击 Unbatch 后开发者工具变为空白。
   -  devtools 中 Text 节点的文字显示为 undefined。

## 1.4.8(2018.11.7)

1. 支持编译成支付宝小程序，通过在`<anu-xx instanceUid={uuid}>`这种机制解决支付宝小程序的实例生成顺序与React实例生成顺序不一致的问题
2. 修复快应用的文本节点不显示问题，自动为它添加<text>标签包含它
3. 添加patchComponent机制
4. 修复样式表中的@assets别名问题

## 1.4.7(2018.10.29)

1. 微信小程序的组件机制由template改成自定义组件机制实现， 解决文本节点保留换行符的问题
2. 支持编译成百度智能小程序
3. 支持编译成快应用
4. 模板的开发目录改成source，生产目录视构建目标有所不同

请百度 jQuery的事件委托
