### ISSUE TITLE
canvas 这些事件要怎么绑定？

### ISSUE THREAD

**Issue by quqiufeng** [RubyLouvre/anu#520]
<canvas class='firstCanvas'
canvas-id="firstCanvas"
bindtouchmove='move'
bindtouchstart='start'
bindtouchend='end'
bindtouchcancel='cancel'
bindlongtap='tap'
disable-scroll='true'
binderror='error'>
</canvas>

**Comment by quqiufeng** [comment]
<canvas class='firstCanvas'
canvas-id="firstCanvas"
bindtouchmove='move'
bindtouchstart='start'
bindtouchend='end'
bindtouchcancel='cancel'
bindlongtap='tap'
disable-scroll='true'
binderror='error'>
</canvas>

**Comment by quqiufeng** [comment]
`<canvas class='firstCanvas'
canvas-id="firstCanvas"
bindtouchmove='move'
bindtouchstart='start'
bindtouchend='end'
bindtouchcancel='cancel'
bindlongtap='tap'
disable-scroll='true'
binderror='error'>
</canvas>
`

**Comment by RubyLouvre** [comment]
这是小程序吗，自己看官网介绍。你应该用touchstart，touchmove吧
