### ISSUE TITLE
路由例子在1.4.9不能用

### ISSUE THREAD

**Issue by yangjy44** [RubyLouvre/anu#525]
路由例子在1.4.4的可以用，但1.4.9不能用
看了一下是，react之前改了e.preventDefaulted=true
```
anchorProps.onClick = function(event){
                        if (fn) {
                            fn(event);
                        }
                        event.preventDefault();//阻止默认的行为，之后preventDefaulted 为true
                        if (shouldNavigate(event)) {// !event.defaultPrevented &&。。  为false，进不来 
                            event.preventDefault();
                            navigate(href, { state, replace });
                        }
                    };
```

**Comment by yangjy44** [comment]
这个代码不是我写的代码，是您写的路由里面的代码

**Comment by yangjy44** [comment]
看了reach的源码，您代码在f (shouldNavigate(event)) {前面面多了event.preventDefault();
您的代码：
anchorProps.onClick = function(event){
                        if (fn) {
                            fn(event);
                        }
                        event.preventDefault();//阻止默认的行为，之后preventDefaulted 为true
                        if (shouldNavigate(event)) {// !event.defaultPrevented &&。。  为false，进不来 
                            event.preventDefault();
                            navigate(href, { state, replace });
                        }
                    };
reach的代码：
 onClick={event => {
                if (anchorProps.onClick) anchorProps.onClick(event);
                if (shouldNavigate(event)) {
                  event.preventDefault();
                  navigate(href, { state, replace });
                }
              }}
            />

**Comment by RubyLouvre** [comment]
已经修复了吧

**Comment by gaterking** [comment]
> 已经修复了吧

router代码修复了，anu的dist还是旧的
