### ISSUE TITLE
使用antd-mobile的时候运行不起来

### ISSUE THREAD

**Issue by howyea** [RubyLouvre/anu#527]
![image](https://user-images.githubusercontent.com/13378079/48976720-c8ed8400-f0c6-11e8-85fe-3d65de71cdac.png)

**Comment by huiyuye** [comment]
其中先后提示说没有react-dom模块、没有rmc-steps模块、没有indexof模块。下载之后还是提示说没有rmc-steps

**Comment by huiyuye** [comment]
是不是因为react中的一些特性，reactWX由于小程序的缘故而无法实现兼容或还没有实现？例如findDomNode？

**Comment by huiyuye** [comment]
像目前react版本迭代也很快，anu在兼容react新版本和react新版本的内容是否适宜小程序这两个问题会如何去取舍和思考？

**Comment by huiyuye** [comment]
最后一个问题就是，当前有适用于anu的UI库吗？有没有必要重新造一个专属的UI库？

**Comment by howyea** [comment]
没有想到，几个月前，还一起讨论问题，说走就走了，有那么一瞬间，我想朝着你的方向努力。天堂有你会更好
