### ISSUE TITLE
建议 nanachi 配置文件，可以提供类似 plugin 的钩子

### ISSUE THREAD

**Issue by ystarlongzi** [RubyLouvre/anu#528]
简单看了下 `nanachi` 的文档和构建命令，发现好像没有预留类似 plugin 的钩子，可以让开发者扩展一些功能，感觉在某些需求就很难实现。比如：

1. 希望根据构建时的 `NODE_ENV` 请求不同的接口地址、或替换部分关键词（类似于 [`webpack-plugin-replace`](https://www.npmjs.com/package/webpack-plugin-replace)）
2. 希望小于 5kb 的图片使用 base64、或压缩图片

**Comment by RubyLouvre** [comment]
正在快速迭代中，后期会改成webpack。
