### ISSUE TITLE
组件中class名字 编译在微信和百度中不一样，百度中会加上 “组件名 + __”

### ISSUE THREAD

**Issue by thisTom** [RubyLouvre/anu#591]
是组件定义有问题 还是 BUG呢 ，好急

**Comment by thisTom** [comment]
最新demo中也有这个问题。只要是组件，在百度中组建内的class名都会被加上“组件名+__”。这个问题会导致css没法写。咋整呐

**Comment by RubyLouvre** [comment]
没有啊，样式能正常显示

**Comment by thisTom** [comment]
> 没有啊，样式能正常显示

很冒犯的给您“cheng19840218@gmail.com”发送了一封邮件，贴了一张图。
BUY场景拼多多模板是在百度小程序最新开发者工具中中，所有component里的组件class名字都被添加了‘anu-’ + 组件名 + class名。

**Comment by thisTom** [comment]
找出原因了    所有跟这个组件相关的样式必须放在组件目录的index中 demo 中很多地方跟文档要求的规范还是有差距的
