### ISSUE TITLE
React Developer Tools 显示空白，无法进行调试。

### ISSUE THREAD

**Issue by harrydengchao** [RubyLouvre/anu#595]
# React Developer Tools 显示空白，无法进行调试。

--- 

`anujs`: 1.4.9
`node`: 10.13.0
`Chrome`: 版本 69.0.3497.100（正式版本） （32 位）

---

## 问题

* 打开控制台进行调试时，React Developer Tools 显示为空白。

---

## 期望

* 可以使用 React Developer Tools 调试

---

## 现场效果

![image](https://user-images.githubusercontent.com/13941171/50215915-50c16800-03bf-11e9-9b54-4a779811c409.png)

**Comment by RubyLouvre** [comment]
目前不支持，因为实现这个需要框架加许多接口

**Comment by harrydengchao** [comment]
明白了。谢谢司徒老师
