### ISSUE TITLE
能根据不同的构建类型[wx|bu|ali|quick]，dist文件到不同的目录吗

### ISSUE THREAD

**Issue by winnieBear** [RubyLouvre/anu#604]
能根据不同的构建类型[wx|bu|ali|quick]，dist文件到不同的目录吗，例如
* wx构建到dist-wx
* bu构建到dist-bu
不要都构建到dist目录，这样可以多端不用来回切换来查看效果

**Comment by RubyLouvre** [comment]
不能，你可以复制一下，

**Comment by winnieBear** [comment]
如果能根据不同的类型，构建到不同的目录，就可以多个小程序一起看效果，能节省很多时间;或者构建的时候可以传参数指定构建到指定的目录吗？

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/50585339-69497c00-0eaf-11e9-87c2-e7968ba2c0f0.png)

**Comment by RubyLouvre** [comment]
已经支持
