### ISSUE TITLE
构建出来的dist/pages/demo/syntax/await/index.js 的 regeneratorRuntime 的引用地址不对

### ISSUE THREAD

**Issue by winnieBear** [RubyLouvre/anu#605]
// var regeneratorRuntime = require("../../../../../node_modules/regenerator-runtime/runtime.js");  应该是 var regeneratorRuntime = require("../../../../npm/regenerator-runtime/runtime.js");

**Comment by RubyLouvre** [comment]
哪一个版本，最后放一个github地址，我们瞧瞧

**Comment by RubyLouvre** [comment]
是什么小程序

**Comment by RubyLouvre** [comment]
先将你之前的命令unlink,使用npm上的源吧
![image](https://user-images.githubusercontent.com/190846/50390464-672a4380-0772-11e9-825e-30af826a6226.png)

**Comment by RubyLouvre** [comment]
我让同事在window下测试一下

**Comment by RubyLouvre** [comment]
已经修复，今天晚上出一个版本
