### ISSUE TITLE
request方法可以支持cookie管理么

### ISSUE THREAD

**Issue by thisTom** [RubyLouvre/anu#607]
马上题测试了。发现cookie不支持

**Comment by RubyLouvre** [comment]
你有什么提议，我们内部的版本是支持了。目前这个request是基于微信小程序的API做Promise封装的，不想添加太多其他功能

**Comment by thisTom** [comment]
我是用的weapp-cookie这个库来解决了。修改源码成react.api风格很简单 似乎没发现bug，最好可以提供一个这样的插件，供需要的人使用，这样就太方便了

**Comment by wenchaoss** [comment]
> 我是用的weapp-cookie这个库来解决了。修改源码成react.api风格很简单 似乎没发现bug，最好可以提供一个这样的插件，供需要的人使用，这样就太方便了

我们是在框架的基础上 额外封装了请求的方法。

**Comment by wenchaoss** [comment]
> 我是用的weapp-cookie这个库来解决了。修改源码成react.api风格很简单 似乎没发现bug，最好可以提供一个这样的插件，供需要的人使用，这样就太方便了

支付宝是不支持前端设置cookie，但是支持后端set-cookie
微信支持前端设置cookie，但是不支持后端set-cookie

可以通过请求成功的回调拦截set-cookie（const setCookie = res.header['Set-Cookie'] || res.header['set-cookie'];   百度是小写），设置到本地的缓存内，在请求前手动设置header.cookie。这样就可以保证后端的set-cookie在微信的兼容

**Comment by thisTom** [comment]
> > 我是用的weapp-cookie这个库来解决了。修改源码成react.api风格很简单 似乎没发现bug，最好可以提供一个这样的插件，供需要的人使用，这样就太方便了
> 
> 我们是在框架的基础上 额外封装了请求的方法。

weapp-cookie也是这个原理的
