### ISSUE TITLE
支付宝小程序的page页面构建的代码缺少page.json

### ISSUE THREAD

**Issue by winnieBear** [RubyLouvre/anu#610]
支付宝小程序每一个page都需要对应的index.json,目前娜娜奇构建出的page，如果页面中没有引用组件，就没有index.json这个文件，导致编译报错

**Comment by RubyLouvre** [comment]
不会啊，我们的支付宝小程序都上线

**Comment by RubyLouvre** [comment]
你把错误贴上来

**Comment by winnieBear** [comment]
可能是支付宝小程序的开发者工具因为其他错误误报了，之前是我添加了index.json，错误就消除了；现在没有也不报错了，多谢
