### ISSUE TITLE
运行nanachi watch报错

### ISSUE THREAD

**Issue by jerryjiao** [RubyLouvre/anu#632]
现象：
刚装上nanachi-cli
nanachi init 一个项目，
yarn以后，
跑nanachi watch:wx会报错
报错截图
![image](https://user-images.githubusercontent.com/12718716/50754799-de42fa00-1291-11e9-9926-d80186c28d66.png)
Node也在8.6以上了
求问是什么问题？

**Comment by RubyLouvre** [comment]
不能出现 中文吧

**Comment by jerryjiao** [comment]
是不能出现中文，谢谢~
