### ISSUE TITLE
Can't resolve 'react-dom/server

### ISSUE THREAD

**Issue by mydearxym** [RubyLouvre/anu#640]
Can't resolve 'react-dom/server' in '/Users/xieyiming/code/coderplanets/coderplanets_web/node_modules/react-svg/es' 

webpack config: 
![image](https://user-images.githubusercontent.com/6184465/51049602-4f274080-1609-11e9-8c49-fb3d91049652.png)

detail: 
![image](https://user-images.githubusercontent.com/6184465/51049575-361e8f80-1609-11e9-9f59-b48fcc46be90.png)

![image](https://user-images.githubusercontent.com/6184465/51049799-e8565700-1609-11e9-9371-eec96ecbafd5.png)

https://github.com/tanem/react-svg/blob/master/src/index.tsx#L4 

请问下是否有 `react-dom/server` 的 alias ?

**Comment by yuchonghua** [comment]
```
import ReactDOMServer  from 'anujs/dist/ReactDOMServer'
```
[![image](https://user-images.githubusercontent.com/17898715/51069744-d60f0400-166f-11e9-9bf1-e8f838b627e1.png)](https://rubylouvre.github.io/anu/ch/ssr.html)

**Comment by mydearxym** [comment]
@yuchonghua 谢谢， 但是这是第三方的 lib, 直接改源码很麻烦

**Comment by mydearxym** [comment]
这个问题有人遇到过并且提出过 PR: https://github.com/RubyLouvre/anu/pull/40/commits 
但是没有任何说明就被关了。。 @RubyLouvre

**Comment by yuchonghua** [comment]
支持一下

**Comment by mydearxym** [comment]
问题是这个代码不是我自己的，是一个第三方的工具库源码内部用了

```js
import ReactDOMServer from 'react/server'
```

我不太可能去自己这个库的源码或者 fork 修改再发布。

如果有 ReactDOMServer 的 alias 就能很好的解决了

**Comment by HadiChen** [comment]
是的，能有这个alias 就能很好了

**Comment by yuchonghua** [comment]
期待一个[pr](https://github.com/RubyLouvre/anu/pull/40)

**Comment by RubyLouvre** [comment]
你重新提一下PR啊

**Comment by yuchonghua** [comment]
@mydearxym 你重新创建个pr把

**Comment by mydearxym** [comment]
我 fork 以后简单做了一个 alias 的映射:
https://github.com/mydearxym/anu/blob/master/webpack.config.js#L79

```diff
    resolve: {
      
        extensions: [ '.js'],
        alias: {
            react: path.resolve(__dirname, './dist/React.js'),
            'react-dom': path.resolve(__dirname, './dist/React.js'),
+           'react-dom/server': path.resolve(__dirname, './dist/ReactDOMServer.js')
        }
    },
```

并且在我自己项目的 webpack config 添加了 react-dom/server 的 alias
```js
  config.resolve.alias = {
      react: 'anujs',
      'react-dom': 'anujs',
      'react-dom/server': 'anujs',
      'prop-types': 'anujs/lib/ReactPropTypes',
  }
```
结果还是报同样的错误，找不到 'react-dom/server'。好像 alias 没有起作用，求助。。
