### ISSUE TITLE
入群二维码过期啦

### ISSUE THREAD

**Issue by liuv1118** [RubyLouvre/anu#696]
入群二维码过期啦，有什么其他的官方微信群吗

**Comment by shaoyudong** [comment]
最新二维码
![411547729622_ pic](https://user-images.githubusercontent.com/16398401/52927213-5cf08400-3374-11e9-9f54-ccbad8b61ea7.jpeg)

**Comment by shaoyudong** [comment]
> 入群二维码过期啦，有什么其他的官方微信群吗
最新二维码
![411547729622_ pic](https://user-images.githubusercontent.com/16398401/52927213-5cf08400-3374-11e9-9f54-ccbad8b61ea7.jpeg)

**Comment by RubyLouvre** [comment]
QQ号： 793771794
