### ISSUE TITLE
__events赋值问题

### ISSUE THREAD

**Issue by aaawhz** [RubyLouvre/anu#70]
dom.__events 是什么时候赋值的， 很奇怪

经过了这个方法  action = strategyCache[which] = getPropAction(dom, name, isSVG);

dom的events属性突然就有值了， 但这里面并没有看到给dom新增__events属性啊

**Comment by RubyLouvre** [comment]
```
   event: function (dom, name, val, lastProps) {
        let events = dom.__events || (dom.__events = {});
```
