### ISSUE TITLE
微信小程序：pageJSON["navigationBarTextStyle"] 字段需为 black 或 white

### ISSUE THREAD

**Issue by lyf7** [RubyLouvre/anu#740]
![image](https://user-images.githubusercontent.com/38553953/53734755-e1d4b500-3ebf-11e9-8053-4043a8420192.png)

**Comment by taotao9125** [comment]
@lyf7 ，你微信开发者工具版本是都少？

**Comment by lyf7** [comment]
@taotao9125  v1.02.1901230
这应该不是开发工具的问题。
![image](https://user-images.githubusercontent.com/38553953/53740910-3aac4980-3ed0-11e9-8164-ccc6a786aa4a.png)

**Comment by taotao9125** [comment]
@lyf7 ，不影响你开发的情况下，开发工具建议先退回到上一个稳定版本 (1.02.1812271)，后续我们会修复该问题。

**Comment by lyf7** [comment]
好的，谢谢啦。
