### ISSUE TITLE
异步渲染不能按照预期位置显示

### ISSUE THREAD

**Issue by kmvan** [RubyLouvre/anu#84]
做了一个简单的 demo, react 16.2 是能按照 123 预期位置显示, 但 au 会相反.
https://github.com/kmvan/test-anujs-async-render

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/34427891-0770c2fe-ec82-11e7-96a4-f20d10fbc59b.png)
1.2.1就是输入这样的

**Comment by kmvan** [comment]
1.2.1 更新后正常. 感谢修复.
