### ISSUE TITLE
devtools: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dgeibi** [RubyLouvre/anu#86]
![deepinscreenshot_select-area_20171230114856](https://user-images.githubusercontent.com/2224764/34451130-9dcb9cb2-ed57-11e7-8d23-7faf81cbed56.png)
![deepinscreenshot_select-area_20171230114241](https://user-images.githubusercontent.com/2224764/34451132-a078e384-ed57-11e7-87eb-699dd0bbbb3d.png)

**Comment by RubyLouvre** [comment]
最好给例子

**Comment by dgeibi** [comment]
遇到问题的 repo 是 https://github.com/dgeibi/player

测试了下面的简单例子，也有这个问题

``` js
import React from 'react'
import ReactDOM from 'react-dom'

const render = () => {
  ReactDOM.render(
    <span>1</span>,
    document.getElementById('root')
  )
}

if (process.env.NODE_ENV === 'development') {
  if (!process.env.REACT) {
    require('anujs/lib/devtools.js')
  }
}

render()
```

**Comment by dgeibi** [comment]
感谢大大年末更新修复开发工具！

经测试，有一个小问题：

https://github.com/RubyLouvre/anu/blob/e725ca8ba3e089670654c973876bde2b1afb292e/lib/devtools.js#L192

`instanceMap.get(vnode)` 有 `undefined` 的情况，在 `visitNonCompositeChildren` 函数开头加上 `if (!instance) return` 可以修复这个问题

**Comment by RubyLouvre** [comment]
放假回来再看吧

**Comment by dgeibi** [comment]
谢谢！
