### ISSUE TITLE
Could not replace react well

### ISSUE THREAD

**Issue by JounQin** [RubyLouvre/anu#87]
1. prop-types shape isRequired
2. Component constructor
3. renderToNodeStream

Reproduction: https://github.com/JounQin/react-study/blob/anujs/build/base.js#L54-L58

comment anujs alias and run `yarn dev`, it works.

**Comment by RubyLouvre** [comment]
Come back after vacation

**Comment by RubyLouvre** [comment]
例子跑不起来
npm run build
npm run start

![image](https://user-images.githubusercontent.com/190846/34513701-7d29eb30-f0a4-11e7-82ba-f7897d4e1869.png)

**Comment by JounQin** [comment]
@RubyLouvre 呃，node 版本过低了，koa 现在用 async/await 要求 node 7.10.1+ 了，这是一个 SSR 项目，后端部分没有进行打包编译

**Comment by JounQin** [comment]
@RubyLouvre 或者使用开发环境 `npm run dev`

**Comment by RubyLouvre** [comment]
好了

最近的升级如下：

1. PropTypes的share问题
```
var check = function () {
        return check;
    };
```
2. utils的inherit BUG 
3. ssr模块的renderToNodeStream的支持
4. Component添加isReactCompent方法，增加对第三方的支持

**Comment by JounQin** [comment]
That works.

**Comment by JounQin** [comment]
@RubyLouvre 呃，刚把 [react-hackernews](https://github.com/JounQin/react-hackernews/tree/anujs) 增加了 anujs 的 alias，再开发环境一切正常，但是生产环境打包时 ReactRouter 就无法正确工作了，点击应用内链接地址栏 url 变了但是路由内容无法显示，也没有任何报错，去除 alias 时打包启动应用没有问题。

复现步骤：
``` bash
yarn dev // 开发模式启动应用，打开 http://localhost:4000 点击导航条切换，正常运行
yarn build // 生产模式打包
yarn start // 生产模式启动，打开 http://localhost:4000 点击导航条切换，无法正常运行
// 去除 https://github.com/JounQin/react-hackernews/blob/anujs/build/base.js#L72-L74 处的 alias 重新打包启动，正常运行
```

**Comment by JounQin** [comment]
刚尝试把其他依赖升级到了最新版本，路由可以点击了，但是跟 [react-transition-group](https://github.com/reactjs/react-transition-group) 似乎兼容有问题，还是上面的复现仓库，路由切换的效果和 react 版差别很大，可以与 https://react-hn.now.sh 对比，而且从其他路由切换到 /show 页面时有一定概率上面多一个空 li ，生产模式出现的概率比较大。

![jietu20180106-213716 2x](https://user-images.githubusercontent.com/8336744/34640229-cf653aa8-f329-11e7-956d-6f0741fb8cc6.jpg)

**Comment by RubyLouvre** [comment]
我看看

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/34661785-f6d025ea-f486-11e7-9d9f-14dba0e24d8c.png)

**Comment by JounQin** [comment]
@RubyLouvre 复现是在 `anujs` 分支，master 上 `koa-webpack` 升级有问题，刚暂时回退了。

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/34664737-372ad872-f498-11e7-848c-0b59a6b97b3d.png)

**Comment by RubyLouvre** [comment]
![image](https://user-images.githubusercontent.com/190846/34665127-0f20fe68-f49a-11e7-93f8-81701fb5d5b6.png)

**Comment by RubyLouvre** [comment]
也不行

**Comment by RubyLouvre** [comment]
要不要翻墙拉数据

**Comment by JounQin** [comment]
数据是需要翻墙的，内部用的 HN 的 firebase API.

**Comment by RubyLouvre** [comment]
翻了页面也打不开

**Comment by JounQin** [comment]
呃，这是个 SSR 项目，不止浏览器端需要翻墙，后台终端也需要翻墙，类似问题
https://github.com/vuejs/vue-hackernews-2.0/issues/241

**Comment by RubyLouvre** [comment]
试过了，不行，17大后 墙变高了，那么搞不定

**Comment by RubyLouvre** [comment]
其实你只是一个React例子，没有搞这么复杂的后台，你把它的前几页面数据保存到一个大JSON中，然后就可以愉快地跑起来

**Comment by JounQin** [comment]
@RubyLouvre 我把 anujs 分支临时支持了非 SSR 模式，现在只需要浏览器端翻墙就行了，可以试试 SS 全局代理？这个项目本身是为了演示 [react-server-renderer](https://github.com/JounQin/react-server-renderer) 的，数据肯定是动态获取最新的更好。

**Comment by RubyLouvre** [comment]
现在还闪烁吗？

**Comment by JounQin** [comment]
@RubyLouvre 升级了一下倒是不闪烁了，但是元素经常会错乱……

![jietu20180202-125932](https://user-images.githubusercontent.com/8336744/35717260-02b5cf0e-0819-11e8-9dcf-58a78d178b01.gif)

图里鼠标点击的地方应该是 Prev 和 More

**Comment by JounQin** [comment]
目前最新版替换后运行正常了
