### ISSUE TITLE
默认模板显示界面有问题

### ISSUE THREAD

**Issue by henryzp** [RubyLouvre/anu#882]
使用cli init了一个项目，默认模板。

```sh
npm i
nanachi watch:wx
```

开发者工具用的最新版。

`Welcome`组件并没有得到渲染，但是能进`render`方法。

![image](https://user-images.githubusercontent.com/3849702/56008292-5cd68a00-5d0e-11e9-8160-4fbc6ab5410a.png)

**Comment by RubyLouvre** [comment]
这是版本问题吧
