### ISSUE TITLE
请问官方支持react-redux吗？

### ISSUE THREAD

**Issue by foresightyj** [RubyLouvre/anu#892]
你在 #305 里面的例子，是没有使用react-redux的。
我使用react-redux的时候遇到的错误是：

![image](https://user-images.githubusercontent.com/1296736/56103877-92c27b00-5f67-11e9-8ee3-d8b15c8fb85c.png)

这是react-redux的代码。使用了react的demo属性。
![image](https://user-images.githubusercontent.com/1296736/56103941-e9c85000-5f67-11e9-9184-3edb7e269940.png)

我看anu.js里面是不支持这个memo的功能的。是不是代表使用anu的时候，只能使用redux (通过reduxIE)，不能使用react-redux?

**Comment by RubyLouvre** [comment]
还不支持memo

**Comment by foresightyj** [comment]
嗯。非常感谢！估计与reactie一样使用5.0.7版本的react-redux就行了，那个版本的源码里面没有memo的使用。
