### ISSUE TITLE
reduxIE.js在Object.getPrototypeOf上面报错

### ISSUE THREAD

**Issue by foresightyj** [RubyLouvre/anu#893]
我在你anu-ie8-example的例子的基础上小试了一下reduxIE，遇到了Object.getPrototypeOf的错误。我将示例代码放在这边：
https://github.com/foresightyj/anu-ie8-example/commits/master

我增加的代码很少，就是一个number状态，读出来显示在界面上而已。

![image](https://user-images.githubusercontent.com/1296736/56114915-c962ba80-5f94-11e9-8331-fc6175c2463e.png)

我试了使用es5-sham之后，ie8加载的时候，浏览器卡死了。

我也看过你的 #305 例子，不过这个例子只是代码片段，不是一个项目。从其他渠道也没有看到一个使用reduxIE的例子。

**Comment by RubyLouvre** [comment]
https://github.com/RubyLouvre/anu/commit/ed854acbc69a30181d4b87c7c8e5a98b9c8e8caf#diff-13b92cdf489f349678a7a7e73a41a937
我升级一下

或者使用这个 https://github.com/ambit-tsai/reactie

**Comment by RubyLouvre** [comment]
https://stackoverflow.com/questions/10919915/ie8-getprototypeof-method

**Comment by foresightyj** [comment]
非常感谢! 我直接覆盖你的新代码到本地的node_modules下面的anujs/libs/ReduxIE.js，build之后遇到的新的问题：

![image](https://user-images.githubusercontent.com/1296736/56121451-bbb43180-5fa2-11e9-823e-712fec8f23b9.png)

**Comment by foresightyj** [comment]
@RubyLouvre 请问你能考虑将reduxIE的例子，加到anu-ie8-example里面吗？
我从一个已有的能够跑的例子，比较容易慢慢的适配到我的应用里面来。

**Comment by foresightyj** [comment]
@RubyLouvre 昨天稍微看了一下redux源码，今天又试了一下，发现你上次的代码有一个粗心，就是hasOwn没有被定义。

我增加了：

        var hasOwn = Object.prototype.hasOwnProperty;

之后，reduxIE就跑起来了。

谢谢作者！
