### ISSUE TITLE
`children中存在非法的对象`?

### ISSUE THREAD

**Issue by JounQin** [RubyLouvre/anu#90]
复现仓库：https://github.com/JounQin/1stg/blob/anujs/build/base.js#L79-L80
分支：anujs
执行：`yarn dev`，访问 http://localhost:4000
React 版本运行正常

**Comment by RubyLouvre** [comment]
已经去掉这个报错了

应该是你的虚拟DOM用了函数，原来不支持children为函数，升级就好了

**Comment by JounQin** [comment]
@RubyLouvre 用的就是最新版本

**Comment by JounQin** [comment]
刚在另一个项目发现使用 React 也有问题，仔细看了下最近升级的依赖，调试发现是 react-hot-loader 升级 react-stand-in 后开始出现问题，不是 anujs 的问题。

**Comment by RubyLouvre** [comment]
我看看

**Comment by RubyLouvre** [comment]
react-stand-in的行为好怪啊

**Comment by JounQin** [comment]
嗯，跟 `react-stand-in` 报 issue 了，这个不是 anujs 的问题

**Comment by RubyLouvre** [comment]
React Hot Loader用到react-proxy，react-proxy用到deepForceUpdate
```
import React from 'react';
import { render } from 'react-dom';
import deepForceUpdate from 'react-deep-force-update';

const instance = render(<Something />);

// Will force-update the whole rendered tree
// even if components in the middle of it
// define a strict shouldComponentUpdate().
deepForceUpdate(instance);
```

**Comment by JounQin** [comment]
@RubyLouvre `_reactInternalFiber` 这个名称还没有调整吗？
