### ISSUE TITLE
renderToString 与renderToStaticMarkup 现在代码是一样的了，是因为，去除了renderToStaticMarkup吗

### ISSUE THREAD

**Issue by yuchonghua** [RubyLouvre/anu#917]
![8017296719FDBD8F18801B1684003081](https://user-images.githubusercontent.com/17898715/56471265-16f29200-6483-11e9-9cfd-d4f36de899e4.png)

**Comment by RubyLouvre** [comment]
是的，看 preact也差不多一样的实现

**Comment by yuchonghua** [comment]
也实现了客户端激活吗
