### ISSUE TITLE
为什么去掉了Object.assign呢？

### ISSUE THREAD

**Issue by kungfuboy** [RubyLouvre/anu#92]
是有啥bug吗？还是性能不够极致？
呃，其次我也不理解，既然用了ES6，为什么还用着var关键字呢？

**Comment by RubyLouvre** [comment]
因为用了Object.assign，有时用户忘带引入babel-polyfill,就来投诉，说多了也烦，直接改用这个。并且extend比Object.assign性能高。

你用了let，浏览器也会翻译成 var
