### ISSUE TITLE
nanachi watch 报错

### ISSUE THREAD

**Issue by chentongji** [RubyLouvre/anu#984]
Windows平台下使用nanachi cli创建默认模板可以构建项目，但是创建除默认模板之外的如拼多多模板在构建时会报错  **Error: Source and destination must not be the same.**
请问这是什么原因？

**Comment by RubyLouvre** [comment]
从来没有遇到这问题
```
nanachi init aaa; 
nanachi watch:wx;
```

**Comment by taotao9125** [comment]
@chentongji  已复线，下一个版本解决掉。

**Comment by taotao9125** [comment]
@chentongji  nanachi-cli@1.2.4 已发布。
