### ISSUE TITLE
建议更新一下anujs的手脚架

### ISSUE THREAD

**Issue by appbest** [RubyLouvre/anu#99]
里面的包比较旧，造成使用困扰
https://github.com/Levan-Du/anu-cli

**Comment by RubyLouvre** [comment]
正在搞一个新的 https://github.com/RubyLouvre/anu-cli

**Comment by liuliangsir** [comment]
issue 名字有点问题，应该是脚手架吧，建议修改一下

**Comment by RubyLouvre** [comment]
时代是不断进步，转眼间，fetch有了abort, Promise有了finally, class有了静态、私有属性，  页面性能优手段从requestAnimationFrame，InsterSectionObserver到requestIdleCallback不断累积，js也开始支持bigint。React也不是我们熟悉的React，从0.14起，官方不知出了多少个最好实践，然后不断打脸自己。因此我们是时间翻一翻官网或源码了，看React16变成什么样子。

React16早期三大特性：
组件支持返回数组。这是一个千呼万唤的功能，因此有的情况真的不能包一层，像td，li就不能包一个div，因为外面已经有一个tr或ul....
React.createPoral, 俗称传送门。早期React生成的节点该挂在什么元素下，是不可改变的，于是有了unstable_renderSubtreeIntoContainer这样的怪异手段，害得官方迟迟不能废弃这个API 。这个新API 还有一个好处时，它的事件冒泡是沿着虚拟DOM进行，而不是真实DOM，这样会解决一些逻辑上的问题。
componentDidCatch，错误边界，一个新生命周期钩子，其他钩子，render, ref，组件contructor出错，它就会唤起。它会在componentDidMount/Update后执行。它的传参有一个详细的组件包嵌栈，清晰地告诉你哪个组件有问题，是在哪个方法中。有了它，不用你到处写 try catch了。

React16.1~2
<Fragment/>组件闪亮登场，这其实相当于一个数组，只是他们不想写数组间的逗号。加上babel加持的语法糖，`<><span /><span/></>`,实在不能更爽了。但这也开了一坏头，babel已经不能中立了。不过谁叫babel 的作者被facebook收编了呢，肯定要为老板开个小灶。
compoentWillXXX要退出历史，被废弃掉。多了一个叫`getDerivedStateFromProps`的静态方法代替componentWillReceiveProps，它会生成一个新state，方便让你setState，所有生命周期钩子（除了构造器），context传参都被下岗了。
推出<StrictMode/>组件，有点像es6的严格模式。因为多出了一些生命周期，内部肯定多跑一些代码，在严格模式下，声明被废弃的compoentWillXXX就不会被调用。相信以后有越来越多被废弃的方法会加入这个白名单中。
推出new Context API。context是一种跨层级的数据传送方案，被react-redux 与react-router所深度使用。但要使用context非常恶心，首先顶层，默认有一个空对象，作为顶级context往下传，传到某个子组件，它有一个getChildContext方法，那么它返回的对象与上层的context进行合并，继续往下。但这个子组件的子孙想用这个新context （官方源码称之为unmaskedContext），需要一些手续。就是在type里面定义contextTypes，然后根据contextTypes的键名再从这个新context扒出一个子集（官方源码称之为maskedContext） ,然后这个子子组件就可以高兴享用它了。但这个子子组件的孩子，子子子组件用什么context 呢，什么也没有，unmaskedContext只是路过它，但一条毛都没有给它，它只拿到一个空对象。在React16新架构中，context 受尽冷眼，首先它的搭档PropTypes已经打进冷宫，其次，内部许多方法不再接受context传参。fiber架构通过contextStack, beginWork, finishWork等方法巧妙地解决React5低效的传输问题，并且也解了 shouldComponentUpdate return false的意外。createContext会生成两个组件（Provider，Consumer），通过观察者模式建立关联，跳过中间N 多组件，直接触发Consumer下方的组件更新。这其实有许多内容，以后有机会再分享详述。
推出createRef与forwardRef, 这是解决refs对象的原罪。React会产生元素节点，但如果获得元素节点的引用是一个难题，于是推出了string ref与function ref。string ref有重大缺点，一个div需要知道是哪个组件render了自己，于是内部就有一个叫currentOwner的全局对象，每当组件实例化后，就把实例放到这上面，当下面的div, span在执行React.createElement(div/span, props, ...children)时， currentOwner会神不知鬼不觉到混进内部，作为ReactElement的第6个参数_owner。React.createElement只是ReactElement的外壳，一个加工厂，ReactElement的返回值才是我们熟悉的虚拟DOM 。但currentOwner.current会改来改去，并且针对一些恶心情况做了许多补丁。随着React 以后会考虑WebWorker方式进行更新，这全局的东西肯定是障碍。于是有了createRef，返回一个object ref，直接能拿到引用，它能早于组件诞生，方便用户操作。forwardRef是用来指定object ref的活动范围。当然这东西与HOC 也有关，这个有机会也再分享详述。总之，ref与context 一样，从组件中解耦出来。
React一直屈服于redux的恐怖之下，一帮从小众语言转型过来的脑残粉在疯狂吹棒，一些从后端过来的小白大白跟着入局，整个前端界竟然捏着鼻子写着样板代码两年之久。。。虽然也出了许多补救方案，像http请求，包了一层又一层。我们需要量子通信这样简捷的方案。最终等来了，一下子来了三个。new Context API, simple-cache-provider, create-sucription, 尤其是后面两个，对Promise 友好能直接结合await使用，内部与fiber架构的异步机制相关联。这里面的东西太多，本文也不展开了。
fiber架构，这涉及到节点的遍历方式，context切换，requestIdleCallback.

**Comment by liuliangsir** [comment]
司徒大大，`React.cr�eatePoral, 俗称传送门`出现了控制字符，目测司徒大大用的编辑器是VS Code，解决方案可以参考[这个](https://segmentfault.com/a/1190000013357949?_ea=3365421)
