### ISSUE TITLE
兼容IE，npm run bulid 报错

### ISSUE THREAD

**Issue by newyoung21** [RubyLouvre/anu#994]
#### 原项目 react+redux+antd， 引入anu.js 兼容 IE8，webpack（3.0.0）修改如下：

![image](https://user-images.githubusercontent.com/15629504/57856949-ad1a9d80-7820-11e9-8dad-e8bf630c5224.png)

#### npm run build 报下面的错
![image](https://user-images.githubusercontent.com/15629504/57856467-b22b1d00-781f-11e9-8a9c-95472eff1edd.png)

**Comment by RubyLouvre** [comment]
webpack 2呢？

**Comment by newyoung21** [comment]
@RubyLouvre 我加多了 devtools: 'anujs/lib/devtools', 的引入，这个问题就消失了，但我配置了很久还是不能兼容IE8（react + redux + antd）。
![image](https://user-images.githubusercontent.com/15629504/57993851-4aa9f180-7aed-11e9-95cc-edbe15e37881.png)
